### ISSUE TITLE
Bug: FastAPI app is not started when logger is argument of subscriber decorated function (Rabbit)

### ISSUE THREAD

**Issue by darioprencipe** [airtai/faststream#1153]
**Describe the bug**
Provide a clear and concise description of the bug.

My FastAPI application does not start when Logger is included as argument of the subscriber-decorated function than handle incoming events.

I get the following error, I assume this is due to pydantic not serializing the logger when generating docs for asyncapi. Also, I don't know how I can disable asyncapi docs creation.

```
cumana_1    | WARNING:  StatReload detected changes in 'main.py'. Reloading...
cumana_1    | INFO:     Started server process [51]
cumana_1    | INFO:     Waiting for application startup.
cumana_1    | ERROR:    Traceback (most recent call last):
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 705, in lifespan
cumana_1    |     async with self.lifespan_context(app) as maybe_state:
cumana_1    |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
cumana_1    |     return await anext(self.gen)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/broker/fastapi/router.py", line 322, in start_broker_lifespan
cumana_1    |     self.schema = get_app_schema(self)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/asyncapi/generate.py", line 32, in get_app_schema
cumana_1    |     channels = get_app_broker_channels(app)
cumana_1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/asyncapi/generate.py", line 168, in get_app_broker_channels
cumana_1    |     channels.update(h.schema())
cumana_1    |                     ^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/rabbit/asyncapi.py", line 118, in schema
cumana_1    |     payloads = self.get_payloads()
cumana_1    |                ^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/broker/handler.py", line 164, in get_payloads
cumana_1    |     body = parse_handler_params(
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/asyncapi/message.py", line 21, in parse_handler_params
cumana_1    |     body = get_model_schema(
cumana_1    |            ^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/asyncapi/message.py", line 171, in get_model_schema
cumana_1    |     body: Dict[str, Any] = model_schema(model)
cumana_1    |                            ^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/faststream/_compat.py", line 123, in model_schema
cumana_1    |     return model.model_json_schema(**kwargs)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 385, in model_json_schema
cumana_1    |     return model_json_schema(
cumana_1    |            ^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 2158, in model_json_schema
cumana_1    |     return schema_generator_instance.generate(cls.__pydantic_core_schema__, mode=mode)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 413, in generate
cumana_1    |     json_schema: JsonSchemaValue = self.generate_inner(schema)
cumana_1    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 552, in generate_inner
cumana_1    |     json_schema = current_handler(schema)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
cumana_1    |     json_schema = js_modify_function(schema_or_field, current_handler)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 603, in __get_pydantic_json_schema__
cumana_1    |     return __handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
cumana_1    |     json_schema = js_modify_function(schema_or_field, current_handler)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 212, in modify_model_json_schema
cumana_1    |     json_schema = handler(schema_or_field)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 509, in handler_func
cumana_1    |     json_schema = generate_for_schema_type(schema_or_field)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1323, in model_schema
cumana_1    |     json_schema = self.generate_inner(schema['schema'])
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 552, in generate_inner
cumana_1    |     json_schema = current_handler(schema)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 509, in handler_func
cumana_1    |     json_schema = generate_for_schema_type(schema_or_field)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1415, in model_fields_schema
cumana_1    |     json_schema = self._named_required_fields_schema(named_required_fields)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1226, in _named_required_fields_schema
cumana_1    |     field_json_schema = self.generate_inner(field).copy()
cumana_1    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 552, in generate_inner
cumana_1    |     json_schema = current_handler(schema)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 544, in new_handler_func
cumana_1    |     json_schema = js_modify_function(schema_or_field, current_handler)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2012, in json_schema_update_func
cumana_1    |     json_schema = {**handler(core_schema_or_field), **json_schema_update}
cumana_1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 509, in handler_func
cumana_1    |     json_schema = generate_for_schema_type(schema_or_field)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1294, in model_field_schema
cumana_1    |     return self.generate_inner(schema['schema'])
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 552, in generate_inner
cumana_1    |     json_schema = current_handler(schema)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
cumana_1    |     return self.handler(__core_schema)
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 509, in handler_func
cumana_1    |     json_schema = generate_for_schema_type(schema_or_field)
cumana_1    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 769, in is_instance_schema
cumana_1    |     return self.handle_invalid_for_json_schema(schema, f'core_schema.IsInstanceSchema ({schema["cls"]})')
cumana_1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cumana_1    |   File "/app/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 2074, in handle_invalid_for_json_schema
cumana_1    |     raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
cumana_1    | pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'logging.Logger'>)
cumana_1    | 
cumana_1    | For further information visit https://errors.pydantic.dev/2.5/u/invalid-for-json-schema
cumana_1    | 
cumana_1    | ERROR:    Application startup failed. Exiting.
```

**How to reproduce**
Include source code:

```python
import logging
import os
from functools import lru_cache

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from faststream.rabbit import RabbitExchange, RabbitMessage, RabbitQueue
from faststream.rabbit.fastapi import Logger, RabbitRouter  # type: ignore

import config


# Get settings
@lru_cache
def get_settings():
    pass

settings = get_settings()

# Setup StreamRouter and instantiate RabbitMQ broker
router = RabbitRouter(
    settings.rabbitmq_url,
    schema_url="/asyncapi",
    include_in_schema=True,
)
broker = router.broker

# TODO: config
exchange = RabbitExchange("cumana-exchange", durable=True, routing_key="")
sync_queue = RabbitQueue("sync-queue", durable=True, routing_key="")
enrichment_queue = RabbitQueue("enrichment-queue", durable=True, routing_key="")

# Instantiate publisher object
publisher = broker.publisher(queue=enrichment_queue, exchange=exchange, persist=True)


# Declare broker exchanges and queues on application startup
@router.after_startup
async def declare(app: FastAPI):
    await broker.declare_exchange(exchange)
    await broker.declare_queue(sync_queue)
    await broker.declare_queue(enrichment_queue)


...

# Define consumer and producer
### Decorating this function with @publisher and @subscriber implies:
### - given a message received on the subscribed queue, the (@publisher) decorated function output will be delivered to exchange
### - given a message received on the subscribed queue, the (@subscriber) decorated function takes message as input and execute function


@publisher
@broker.subscriber(sync_queue, exchange, retry=3)
async def handle_event(
    input: Input, msg: RabbitMessage, logger: Logger
) -> EnrichedTransaction:
    logger.info(
        {
            "message_id": msg.message_id,
            "correlation_id": msg.correlation_id,
            "message_headers": msg.headers,
            "transaction_id": input.transaction.id,
            "event": "message consumed",
        }
    )
    return do_enrich_transaction(input, nlp)


# Create app
app = FastAPI(
    version="1.0.0",
    lifespan=router.lifespan_context,
)
# Include a StreamRouter object that uses RabbitMQ broker
app.include_router(router)
...
```

And/Or steps to reproduce the behavior:

1. ...

**Expected behavior**
Explain what you expected to happen clearly and concisely.

The FastAPI app to start as before

**Observed behavior**
Describe what is actually happening clearly and concisely.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Environment**

 name         : faststream                                                   
 version      : 0.3.14                                                       
 description  : FastStream: the simplest way to work with a messaging queues 

dependencies
 - aio-pika >=9,<10
 - anyio >=3.7.1,<5
 - fast-depends >=2.2.6,<2.4.0
 - typer >=0.9,<1
 - typing-extensions >=4.8.0

**Additional context**
Provide any other relevant context or information about the problem here.

**Comment by darioprencipe** [comment]
> bug: Incorrect AsyncAPI payload #1143

@Lancetnik thanks - any shortcut I can use in the meantime? No application logs is definitely a blocker ;-)

Thanks in advance!

**Comment by Lancetnik** [comment]
@darioprencipe, sorry, you can't fix it without patching this [method](https://github.com/airtai/faststream/blob/main/faststream/broker/fastapi/router.py#L322)

Anyway, I hope to upload a fix tomorrow

**Comment by Lancetnik** [comment]
@darioprencipe I found the problem in your code

If you are using **FastAPI** plugin you should use

```python
from faststream.rabbit.fastapi import RabbitMessage
# instead of
from faststream.rabbit import RabbitMessage
```

and

```python
@router.subscriber(...)
# instead of
@broker.subscriber(...)
```

We have some problems with AsyncAPI generation, but not in this case. It just an incorrect usage, sorry.

**Comment by Lancetnik** [comment]
Regular `faststream.*` Context object are compatible only with regular `broker.subscriber`.
But `faststream.*.fastapi` Context is compatbile with **FastAPI** case only. You can't mix them.

**Comment by darioprencipe** [comment]
@Lancetnik thanks a lot for the prompt reply, that solved indeed. 

Little feedback: maybe in FastAPI integration docs, this could be better shown / explained (example when you use your custom payload + Rabbit Message + Logger to handle a proper control flow with e.g. try / except + ack / nack / reject logic. Also from the discussions section, seems like many people want to be able to do that somehow and, at the moment, the FastAPI integration page is a big tight on examples.

**Comment by Lancetnik** [comment]
@darioprencipe thanks for your notice!

**FastStream - FastAPI** is just a one page of our doc and it shouldn't describe all possible framework features (user can find them at other pages). FastAPI integration describes only the things, related to FastAPI or different from default FastStream behavior. This reason we already has a note about different `Context` usage (with link to the original `Context` one).

Probably, we can make it much clear, I'll think about this notice refactoring. If you have any ideas about, I'll be glad to merge your PR!
