### ISSUE TITLE
Bug: Nested FastAPI router can't return / publish messages

### ISSUE THREAD

**Issue by strangemonad** [airtai/faststream#1206]
**Describe the bug**
Following the instructions in [Router Nesting](https://faststream.airt.ai/latest/getting-started/integrations/fastapi/#routers-nesting), it seems like a nested router can't return / publish a message

See the code attached. Even though the handler is given the root connection in broker.py:228 (`Broker.start`) the nested handler holds a copy of the nested broker, which hasn't been started by the lifespan. Logs and stack trace attached at the end.

**How to reproduce**

The repro case attempts to be as minimal as possible (single-threaded uvicorn with asyncio run loop + nats client). The Test Clients don't end up fulling triggering the behavior of a fulling running app.

Run `nats-server` and then run the following code. 

```python
from faststream import FastStream
...
```

And/Or steps to reproduce the behavior:

```python
import asyncio
import threading
from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI
from faststream.nats.fastapi import NatsRouter
from nats.aio.client import Client as Nats

nested_router = NatsRouter()


# XXX this handler definition will capture the `nested_router.broker`, which doesn't get a
# connection or lifespan calls.
@nested_router.subscriber("nested.test")
async def on_nested_test(body) -> str:
    return body


root_router = NatsRouter("nats://localhost:4222")


@root_router.subscriber("test")
async def on_root_test(body) -> str:
    return body


server_ready = threading.Event()


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Other stuff I need to do in FastAPI lifespan
    # then delegate to the root router's lifespan context.
    async with root_router.lifespan_context(app):
        global server_ready
        server_ready.set()
        yield


# root_router will get a copy of the nested_router's handlers but since the handler captures
# the nested_router.broker, the publisher will not work (broker is not started).
root_router.include_router(nested_router)

app = FastAPI(
    lifespan=lifespan,
)
app.include_router(root_router)


async def call_rpc_endpoints():
    nc = Nats()
    await nc.connect("nats://localhost:4222")

    print("calling root")
    msg = await nc.request("test", b"root test")
    assert msg.data == b"root test"

    print("calling nested")
    msg = await nc.request("nested.test", b"nested test")
    assert msg.data == b"root test"


if __name__ == "__main__":
    """Assuming nats on localhost:4222"""
    server_thread = threading.Thread(
        target=uvicorn.run,
        kwargs={
            "app": app,
            "workers": 1,
            "loop": "asyncio",
        },
    )
    server_thread.start()
    server_ready.wait()

    print("calling async rpc endpoints")
    asyncio.run(call_rpc_endpoints())

```

**Expected behavior**

From the FastAPI docs https://fastapi.tiangolo.com/tutorial/bigger-applications/#include-a-path-operation
  >  "The FastApi APIRouters are not "mounted"...

Following how FastAPI "recreates" route handlers rather than "mount" route handlers (and also how FastStream `Broker.include_router` re-creates the nested router's `BrokerRoute`s `broker.core.abc.py:208`, the cleanest approach is probably to re-create the nested handlers and publishers rather than just copy them in `StreamRouter#include_router`  (`fastapi/router.py:618`)

**Observed behavior**

```
INFO:     Started server process [22643]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-02-04 18:21:15,394 INFO     - test        |            - `OnRootTest` waiting for messages
2024-02-04 18:21:15,394 INFO     - nested.test |            - `OnNestedTest` waiting for messages
calling async rpc endpoints
calling root
2024-02-04 18:21:15,396 INFO     - test        | aae6ea64-6 - Received
2024-02-04 18:21:15,396 INFO     - test        | aae6ea64-6 - Processed
calling nested
2024-02-04 18:21:15,396 INFO     - nested.test | e48e66e0-1 - Received
2024-02-04 18:21:15,396 ERROR    - nested.test | e48e66e0-1 - AssertionError: Please, `connect()` the broker first
Traceback (most recent call last):
  File "/Users/shawn/Library/CloudStorage/Dropbox-Personal/Code/instance-bio/instance/services/web/.venv/lib/python3.11/site-packages/faststream/broker/handler.py", line 361, in consume
    raise e
  File "/Users/shawn/Library/CloudStorage/Dropbox-Personal/Code/instance-bio/instance/services/web/.venv/lib/python3.11/site-packages/faststream/broker/handler.py", line 346, in consume
    await publisher.publish(
  File "/Users/shawn/Library/CloudStorage/Dropbox-Personal/Code/instance-bio/instance/services/web/.venv/lib/python3.11/site-packages/faststream/broker/wrapper.py", line 56, in publish
    return await self.method(message, correlation_id=correlation_id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shawn/Library/CloudStorage/Dropbox-Personal/Code/instance-bio/instance/services/web/.venv/lib/python3.11/site-packages/faststream/nats/broker.py", line 489, in publish
    assert self._producer, NOT_CONNECTED_YET  # nosec B101
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Please, `connect()` the broker first
```

**Environment**
`Running FastStream 0.4.1 with CPython 3.11.6 on Darwin`

**Comment by kumaranvpl** [comment]
Hello @strangemonad,

We are refactoring the internal architecture of faststream and this bug is fixed at the refactor branch here - https://github.com/airtai/faststream/tree/big-refactor.
We are working on merging refactored code to main - https://github.com/airtai/faststream/pull/1128
