### ISSUE TITLE
Bug: After Closing a RabbitBroker(), others RabbitBroker() can't publish anymore

### ISSUE THREAD

**Issue by gcadiou** [airtai/faststream#1346]
**Describe the bug**
When opening multiple RabbitBroker(), after you close one of the broker, the others won't be able to publish anymore, if they are used as subscriber they can still listen properly but as soon as you try to await broker.publish(), your function will wait forever.

**How to reproduce**
```python
import asyncio
from faststream.rabbit import RabbitBroker

broker1 = RabbitBroker()
        
async def main():
    await broker1.start()
    while True:
        await broker1.publish(exchange="read_exchange", message="broker_1", routing_key="read_queue")
        async with RabbitBroker() as br:
            await br.publish(exchange="read_exchange", message="broker_2", routing_key="read_queue")
        await asyncio.sleep(2)


asyncio.run(main())
```

**Expected behavior**
Here, on each loop iteration broker1 then broker2 should publish their message.
broker1 connection should remains open, while broker2 should open a new connection and close it each time.

**Observed behavior**
What actually happens is that on first iteration, broker1 and broker2 will properly publish their messages, but on the next iteration the function await broker1.publish() forever.

**Environment**
Python version : 3.11.0rc1
FastStream version : 0.4.6

**Additional context**
Exploring my rabbitmq broker logs, things look normals, 2 connections are opened, one get closed the other remains.

After interrupting process the traceback show this :
```Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/gcadiou/project_test/test4.py", line 12, in main
    await broker1.publish(exchange="read_exchange", message="broker_1", routing_key="read_queue")
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/faststream/rabbit/broker.py", line 511, in publish
    return await self._producer.publish(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/faststream/utils/functions.py", line 128, in fake_context
    yield None
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/faststream/rabbit/producer.py", line 144, in publish
    r = await self._publish(
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/faststream/rabbit/producer.py", line 217, in _publish
    return await exchange_obj.publish(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/aio_pika/exchange.py", line 193, in publish
    channel = await self.channel.get_underlay_channel()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/aio_pika/robust_channel.py", line 79, in get_underlay_channel
    await self._connection.ready()
  File "/home/gcadiou/.local/share/virtualenvs/project_test-pIGUxXDb/lib/python3.11/site-packages/aio_pika/connection.py", line 199, in ready
    await self.connected.wait()
  File "/usr/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/gcadiou/project_test/test4.py", line 21, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 125, in run
    raise KeyboardInterrupt()
KeyboardInterrupt```

**Comment by Lancetnik** [comment]
Works fine with `0.5.0` version
