### ISSUE TITLE
Bug: Unable to process messages when headers() returns null in batch confluent kafka consumers

### ISSUE THREAD

**Issue by andreaimprovised** [airtai/faststream#1459]
**Describe the bug**

Version 0.5.6 added support for batch header processing via this issue: https://github.com/airtai/faststream/issues/1447

The added code expects confluent's cimpl.Messsage.headers() function to always return a tuple:

- https://github.com/airtai/faststream/commit/1bcbcf5a59d4da7d027a52534cb181ba8482f2ac#diff-3ef5eaf17f2a894f317d33a56bf9e084acb2e8959a1bae253a5ebb23f83f881eR56
- https://github.com/airtai/faststream/commit/1bcbcf5a59d4da7d027a52534cb181ba8482f2ac#diff-3ef5eaf17f2a894f317d33a56bf9e084acb2e8959a1bae253a5ebb23f83f881eR93-R96

In fact, it can return None.

This results in an error as follows:

```
2024-05-20 16:32:46.703 | ERROR    | asyncio         | base_events.default_exception_handler:1785 | Task exception was never retrieved
future: <Task finished name='Task-3' coro=<LogicSubscriber._consume() done, defined at venv/lib/python3.11/site-packages/faststream/confluent/subscriber/usecase.py:177> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "venv/lib/python3.11/site-packages/faststream/confluent/subscriber/usecase.py", line 194, in _consume
    await self.consume(msg)  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faststream/broker/subscriber/usecase.py", line 316, in consume
    if (message := await h.is_suitable(msg, cache)) is not None:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faststream/broker/subscriber/call_item.py", line 139, in is_suitable
    "StreamMessage[MsgType]", cache.get(parser) or await parser(msg)
                                                   ^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faststream/confluent/parser.py", line 56, in parse_message_batch
    batch_headers.append(_parse_msg_headers(m.headers()))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/faststream/confluent/parser.py", line 96, in _parse_msg_headers
    return {i: j if isinstance(j, str) else j.decode() for i, j in headers}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

Moreover, this error is not logged to console until the application is exited.

**How to reproduce**

- Using the provectus kafka ui, simply publish a message with no headers on a topic. Or use some other means. Ensure that there are no headers. Do not use faststream, as faststream will always add headers.
- Write a simple faststream consumer handler with `batch=True` subscribed to that topic that merely logs that it received the message.
- Start the FastStream application.

**Expected behavior**

I expect the handler to successfully log.

**Observed behavior**
Nothing is logged, and upon quitting the application, an exception is logged to console.

**Comment by andreaimprovised** [comment]
Returns of `None` by `headers()` is documented here: https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Message.headers
