### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by aronicq** [airtai/faststream#1471]
**Describe the bug**
After an undetected update, imports of faststream's rabbit modules broke.
Even though all versions are fixed on the second digit

**How to reproduce**
```python
from faststream.rabbit import RabbitBroker, RabbitQueue

def init_rabbitmq() -> RabbitBroker:
...
```

**Expected behavior**
Imports do not cause pydantic exceptions 

**Observed behavior**
Imported modules use a pydantic feature that throws an exception 

```
  File "/app/app/adapters/rabbitmq.py", line 1, in <module>
    from faststream.rabbit import RabbitBroker, RabbitQueue
  File "/usr/local/lib/python3.10/site-packages/faststream/__init__.py", line 3, in <module>
    from faststream.annotations import ContextRepo, Logger, NoCast
  File "/usr/local/lib/python3.10/site-packages/faststream/annotations.py", line 6, in <module>
    from faststream.utils.context import Context as ContextField
  File "/usr/local/lib/python3.10/site-packages/faststream/utils/__init__.py", line 1, in <module>
    from fast_depends import Depends
  File "/usr/local/lib/python3.10/site-packages/fast_depends/__init__.py", line 2, in <module>
    from fast_depends.use import Depends, inject
  File "/usr/local/lib/python3.10/site-packages/fast_depends/use.py", line 17, in <module>
    from fast_depends.core import CallModel, build_call_model
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/__init__.py", line 1, in <module>
    from fast_depends.core.build import build_call_model
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/build.py", line 24, in <module>
    from fast_depends.core.model import CallModel, ResponseModel
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/model.py", line 45, in <module>
    class ResponseModel(BaseModel, Generic[T]):
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 541, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 541, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 951, in _common_field_schema
    schema = self._apply_annotations(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1654, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1635, in inner_handler
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 786, in match_type
    return self._unsubstituted_typevar_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1500, in _unsubstituted_typevar_schema
    return self.generate_schema(default)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 814, in match_type
    return self._unknown_type_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing_extensions.NoDefault. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
For further information visit https://errors.pydantic.dev/2.5/u/schema-for-unknown-type
```

**Environment**
Include the output of the `faststream -v` command to display your current project and system environment.
```
/app# faststream -v
Traceback (most recent call last):
  File "/usr/local/bin/faststream", line 5, in <module>
    from faststream.__main__ import cli
  File "/usr/local/lib/python3.10/site-packages/faststream/__init__.py", line 3, in <module>
    from faststream.annotations import ContextRepo, Logger, NoCast
  File "/usr/local/lib/python3.10/site-packages/faststream/annotations.py", line 6, in <module>
    from faststream.utils.context import Context as ContextField
  File "/usr/local/lib/python3.10/site-packages/faststream/utils/__init__.py", line 1, in <module>
    from fast_depends import Depends
  File "/usr/local/lib/python3.10/site-packages/fast_depends/__init__.py", line 2, in <module>
    from fast_depends.use import Depends, inject
  File "/usr/local/lib/python3.10/site-packages/fast_depends/use.py", line 17, in <module>
    from fast_depends.core import CallModel, build_call_model
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/__init__.py", line 1, in <module>
    from fast_depends.core.build import build_call_model
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/build.py", line 24, in <module>
    from fast_depends.core.model import CallModel, ResponseModel
  File "/usr/local/lib/python3.10/site-packages/fast_depends/core/model.py", line 45, in <module>
    class ResponseModel(BaseModel, Generic[T]):
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 541, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 541, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 951, in _common_field_schema
    schema = self._apply_annotations(
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1654, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1635, in inner_handler
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 786, in match_type
    return self._unsubstituted_typevar_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1500, in _unsubstituted_typevar_schema
    return self.generate_schema(default)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 814, in match_type
    return self._unknown_type_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing_extensions.NoDefault. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.5/u/schema-for-unknown-type
```

**Additional context**
running in docker environment

pip freeze:
...
pydantic==2.5.3
faststream==0.5.8
fast-depends==2.4.2
...

also checked with 
faststream==0.3.8

**Comment by Lancetnik** [comment]
It was fixed by 0.5.9 yesterday
