### ISSUE TITLE
Cannot acknowledge a message after certain amount of time

### ISSUE THREAD

**Issue by pasindu-pr** [airtai/faststream#1636]
I have a RabbitMQ subscriber which takes 10 minutes to process a message. Therefore I'm trying to acknowledge the message after the task is complete, so approximately after 10 mins. But when I try to do that it throws a Channel Invalid State Error exception. Do you guys have any recommendations for this kind of scenario?

**Comment by Lancetnik** [comment]
Please, check this option in your RMQ config: https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/deps/rabbit/docs/rabbitmq.conf.example#L602

It should be gt your expected processing time

**Comment by pasindu-pr** [comment]
@Lancetnik  I have already set a consumer timeout policy from the management UI to 30 minutes. But still I get the error. I have added the logs below.

![image](https://github.com/user-attachments/assets/8cb520dd-2e10-4ead-b6fd-80c0b591998c)


`Traceback (most recent call last):
  File "\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File ".venv\lib\site-packages\faststream\utils\context\repository.py", line 117, in scope
    yield
  File ".venv\lib\site-packages\faststream\broker\subscriber\usecase.py", line 355, in process_message
    await h.call(
  File ".venv\lib\site-packages\faststream\broker\subscriber\call_item.py", line 164, in call
    result = await call(message)
  File ".venv\lib\site-packages\faststream\broker\middlewares\base.py", line 64, in consume_scope
    result = await call_next(await self.on_consume(msg))
  File ".venv\lib\site-packages\faststream\broker\wrapper\call.py", line 201, in decode_wrapper
    return await func(msg)
  File ".venv\lib\site-packages\fast_depends\use.py", line 148, in injected_wrapper
    r = await real_model.asolve(
  File ".venv\lib\site-packages\fast_depends\core\model.py", line 533, in asolve
    response = await run_async(call, *final_args, **final_kwargs)
  File ".venv\lib\site-packages\fast_depends\utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
  File ".venv\lib\site-packages\faststream\utils\functions.py", line 53, in to_async_wrapper
    return await call_or_await(func, *args, **kwargs)
  File ".venv\lib\site-packages\fast_depends\utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
  File ".\main.py", line 26, in subscribe_to_index_pdf_file
    await broker.publish(
  File ".venv\lib\site-packages\faststream\rabbit\broker\broker.py", line 612, in publish
    return await super().publish(
  File ".venv\lib\site-packages\faststream\broker\core\usecase.py", line 344, in publish
    return await publish(msg, **kwargs)
  File ".venv\lib\site-packages\faststream\broker\middlewares\base.py", line 102, in publish_scope
    result = await call_next(
  File ".venv\lib\site-packages\faststream\rabbit\publisher\producer.py", line 102, in publish
    r = await self._publish(
  File ".venv\lib\site-packages\faststream\rabbit\publisher\producer.py", line 183, in _publish
    return await exchange_obj.publish(
  File ".venv\lib\site-packages\aio_pika\exchange.py", line 194, in publish
    return await channel.basic_publish(
  File ".venv\lib\site-packages\aiormq\channel.py", line 691, in basic_publish
    await drain_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv\lib\site-packages\faststream\broker\acknowledgement_watcher.py", line 195, in __reject
    await self.message.reject(**self.extra_options)
  File ".venv\lib\site-packages\faststream\rabbit\message.py", line 54, in reject
    await pika_message.reject(requeue=requeue)
  File ".venv\lib\site-packages\aio_pika\message.py", line 480, in reject
    await self.channel.basic_reject(
  File ".venv\lib\site-packages\aio_pika\message.py", line 391, in channel
    raise ChannelInvalidStateError
aiormq.exceptions.ChannelInvalidStateError`

**Comment by Lancetnik** [comment]
Can you show me the subscriber?

**Comment by pasindu-pr** [comment]
@Lancetnik This is how it looks like. At the moment I have make no_ack=True. But I also tried with auto acknowledgement which Fast Stream does itself.
![image](https://github.com/user-attachments/assets/ef957e55-516b-4175-9031-a0f03ca75a68)

**Comment by Lancetnik** [comment]
Can you `index_pdf_file` locks event-loop?

**Comment by Lancetnik** [comment]
I am sure, that the problem is not in the FastStream/aio-pika codebase
For me, now it looks like RMQ lost your subscriber health checks and kills the connection

**Comment by pasindu-pr** [comment]
Thank you @Lancetnik . That was the exact issue. There were some calls which blocked the event-loop. Now it's working fine. One additional question though, is there any equivalent in Fast Stream to set the prefetch count?

**Comment by Lancetnik** [comment]
> Thank you @Lancetnik . That was the exact issue. There were some calls which blocked the event-loop. Now it's working fine. One additional question though, is there any equivalent in Fast Stream to set the prefetch count? 

RabbitBroker(max_workers=...) or smth like

**Comment by Lancetnik** [comment]
So, can we close the issue due u found the problem?

Btw, always welcome, be free to ask anything here or in the discord

**Comment by pasindu-pr** [comment]
Yes sure we can close this & Thank you!
