### ISSUE TITLE
k8s gracefully shutdown

### ISSUE THREAD

**Issue by alteest** [airtai/faststream#1648]
Support k8s gracefully shutdown and wait current message processing

**Is your feature request related to a problem? Please describe.**
When k8s decided to stop pod it send SIGTERM and FasStream app properly receive it, but only wait message processing, but not acknowledged after.
I tried to catch signal by signal.signals and it properly catch, but FastStream also receive it and stop after message processing

**Describe the solution you'd like**
I want to be able after receive SIGTERM wait when message will be processed (with all middlewares processing) and message will be acknowledged.
I want to be able when k8s decided to shutdown pod (using autoscaling) whait when message will be properly process and exit only after

**Describe alternatives you've considered**
Provide a clear and concise description of any alternative solutions or features you've thought about.

**Comment by Lancetnik** [comment]
It should waits for already consumed messages processing and acknowledge as well

**Comment by alteest** [comment]
Ok. Tried to reproduce.
This is code example: nothing special, just conume on queue and use sleep to simulate synchronous processing
```
import logging
import signal
import time
from typing import Any, Callable, Awaitable


from faststream import BaseMiddleware, FastStream
from faststream.broker.message import StreamMessage
from faststream.rabbit import RabbitBroker, RabbitQueue
from faststream.rabbit.annotations import Logger, RabbitMessage
from pydantic_settings import BaseSettings, SettingsConfigDict


logger = logging.getLogger("faststream")


class AppSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file='.env',
        env_file_encoding='utf-8',
        extra='ignore'
    )

    RABBITMQ_HOST: str
    RABBITMQ_PORT: int
    RABBITMQ_VHOST: str = '/'
    RABBITMQ_USER: str
    RABBITMQ_PASSWORD: str
    RABBITMQ_BLOCKING_CONNECTION_TIMEOUT: int = 300
    RABBITMQ_QUEUE: str


settings = AppSettings()


class TestMiddleware(BaseMiddleware):
    async def consume_scope(
        self,
        call_next: Callable[[Any], Awaitable[Any]],
        msg: StreamMessage[Any],
    ) -> Any:
        logger.info('Start TestMiddleware')
        result = await call_next(msg)
        logger.info('Done TestMiddleware')
        return result


broker = RabbitBroker(
    f'amqp://{settings.RABBITMQ_USER}:{settings.RABBITMQ_PASSWORD}@'
    f'{settings.RABBITMQ_HOST}:{settings.RABBITMQ_PORT}/',
    virtualhost=settings.RABBITMQ_VHOST,
    timeout=settings.RABBITMQ_BLOCKING_CONNECTION_TIMEOUT,
    max_consumers=1,
    middlewares=[TestMiddleware]
)
queue = RabbitQueue(settings.RABBITMQ_QUEUE, passive=True)


app = FastStream(
    broker=broker
)


def stop(*args, **kwargs):
    logger.info('Receive termination signal')


@app.on_startup
async def setup(*args, **kwargs):
    signal.signal(signal.SIGINT, stop)
    signal.signal(signal.SIGTERM, stop)


@broker.subscriber(queue)
def on_message(body, logger: Logger, message: RabbitMessage):
    logger.info('Receive message.')
    # Simulate long task
    time.sleep(100)
    logger.info('Done processing message.')
```

On normal processing log:
```
2024-08-07 18:57:39,695 INFO     - Start TestMiddleware
2024-08-07 18:57:39,696 INFO     -      | datafeed.market.production | 28590998-e - Received
2024-08-07 18:57:39,704 INFO     -      | datafeed.market.production | 28590998-e - Receive message.
2024-08-07 18:59:19,566 INFO     -      | datafeed.market.production | 28590998-e - Done processing message.
2024-08-07 18:59:19,566 INFO     - Done TestMiddleware
2024-08-07 18:59:19,567 INFO     -      | datafeed.market.production | 28590998-e - Processed
```

Now during sleep in another terminal I send SIGTERM to simulate k8s scale down (kill -s TERM PID) and this is log (I skipp tracebacks):
```
2024-08-07 19:04:12,209 INFO     - Start TestMiddleware
2024-08-07 19:04:12,209 INFO     -      | datafeed.market.production | 462b490d-b - Received
2024-08-07 19:04:12,218 INFO     -      | datafeed.market.production | 462b490d-b - Receive message.
2024-08-07 19:04:35,092 INFO     - Receive termination signal
2024-08-07 19:04:35,099 INFO     - FastStream app shutting down...
2024-08-07 19:04:35,112 ERROR    -      | datafeed.market.production | 462b490d-b - CancelledError: 
Traceback (most recent call last):
...
  File "/home/alteest/dev/faststream_test/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
2024-08-07 19:04:35,119 INFO     -      | datafeed.market.production | 462b490d-b - Processed
2024-08-07 19:04:35,120 ERROR    -      |                            |            - 
Traceback (most recent call last):
...
  File "/home/alteest/dev/faststream_test/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
File "/home/alteest/dev/faststream_test/venv/lib/python3.10/site-packages/aio_pika/message.py", line 391, in channel
    raise ChannelInvalidStateError
aiormq.exceptions.ChannelInvalidStateError
2024-08-07 19:04:35,129 INFO     - FastStream app shut down gracefully.
2024-08-07 19:05:52,065 INFO     -      | datafeed.market.production | 462b490d-b - Done processing message.
```
Message was processed, there is 'Done processing message.' but as you can see no 'Done TestMiddleware' message in log, so processing not full (middleware processing cancelled).
And also in RabbitMQ Management UI I see that one (1) message was UNACK (because max_consumers=1), but then it return back to READY. So, it was not acknowledged and then wil lbe processed again in another pod

**Comment by Lancetnik** [comment]
@alteest sorry, I have to repeat: can you try to create broker like this and try again, please?

```python
broker = RabbitBroker(
    ....,
    graceful_timeout=30.0,
)
```

**Comment by alteest** [comment]
Nope. As you can see I use sleep(100) and gracefull_timeout is less then message processing time and behaviour is the same.
So, if it's possible that message processing can take 30 minutes, for example. We should setup graceful_timeout to 30 minutes (no less then possible processing)?

If, for example in k8s in deployment.yaml configured grace period to one hour

```
terminationGracePeriodSeconds: 3600
```

then we should setup the same value for broker?

**Comment by Lancetnik** [comment]
Yes, we can't wait forever. Sometimes we should decide, that broker is dead and kill it. This is just a timeout to measure this

**Comment by Lancetnik** [comment]
@alteest is this option the thing you were looking for? Can we close the Issue?

**Comment by Lancetnik** [comment]
Please, reopen the Issue if you want to add smth more here

**Comment by ss14** [comment]
@Lancetnik do the handlers receive any error (like asyncio cancel or timeout error) that can be caught when the graceful_timeout occurs? I would like to save "in-process message" status in db if it does not complete and the timeout occur.
