### ISSUE TITLE
Bug: Setting "group.instance.id" in config dictionary for Confluent KafkaBroker is broken.

### ISSUE THREAD

**Issue by andreaimprovised** [airtai/faststream#1677]
**Describe the bug**

Specifying this setting has no effect, precisely because it is one of the various `config_from_params` settings that take precedence over the passed in configuration dictionary:

https://github.com/airtai/faststream/blob/main/faststream/confluent/client.py#L73C9-L92

There is no other way to specify group.instance.id at this time.

In fact, there is no way to specify a configuration dictionary at the KafkaRouter level, either, which is quite annoying as well.

There may be other currently inaccessible kwargs with defaults in AsyncConfluentConsumer that are clobbering other entries in config as well.

**How to reproduce**

```python
import asyncio
from faststream import FastStream
from faststream.confluent import KafkaBroker, KafkaMessage
from testcontainers.kafka import KafkaContainer
from confluent_kafka import Producer

with KafkaContainer() as kafka:

    producer = Producer({'bootstrap.servers': kafka.get_bootstrap_server()})
    producer.produce('test-topic', value=b'hello')
    producer.flush()

    broker = KafkaBroker(
        kafka.get_bootstrap_server(),
        config={'group.instance.id': 'instance-id-1'}
    )

    @broker.subscriber('test-topic', group_id='group-id', auto_offset_reset='earliest')
    def my_handler(msg: KafkaMessage):
        # This should fail
        assert msg.consumer.config['group.instance.id'] == 'instance-id-1'

    app = FastStream(broker)

    asyncio.run(app.run())

```

And then publish a message to get an AssertionError.

**Expected behavior**
No AssertionError.

**Observed behavior**
```
using host unix:///path/to/socket/docker.sock
Pulling image testcontainers/ryuk:0.7.0
Container started: <container_id_1>
Waiting for container <Container: <container_id_1>> with image testcontainers/ryuk:0.7.0 to be ready ...
Pulling image confluentinc/cp-kafka:7.6.0
Container started: <container_id_2>
Waiting for container <Container: <container_id_2>> with image confluentinc/cp-kafka:7.6.0 to be ready ...
Waiting for container <Container: <container_id_2>> with image confluentinc/cp-kafka:7.6.0 to be ready ...
%3|<timestamp>|FAIL|rdkafka#producer-1| [thrd:localhost:<port>/bootstrap]: localhost:<port>/bootstrap: Connect to ipv6#[::1]:<port> failed: Connection refused (after 0ms in state CONNECT)
%3|<timestamp>|FAIL|rdkafka#producer-1| [thrd:localhost:<port>/bootstrap]: localhost:<port>/bootstrap: Connect to ipv6#[::1]:<port> failed: Connection refused (after 1ms in state CONNECT, 1 identical error(s) suppressed)
Waiting for container <Container: <container_id_2>> with image confluentinc/cp-kafka:7.6.0 to be ready ...
<timestamp> INFO     - FastStream app starting...
<timestamp> INFO     - test-topic | group-id |            - `MyHandler` waiting for messages
<timestamp> INFO     - FastStream app started successfully! To exit, press CTRL+C
<timestamp> INFO     - test-topic | group-id | 0-<message_id> - Received
<timestamp> ERROR    - test-topic | group-id | 0-<message_id> - AssertionError:
Traceback (most recent call last):
  File "/path/to/site-packages/faststream/broker/subscriber/usecase.py", line 355, in process_message
    await h.call(
  File "/path/to/site-packages/faststream/broker/subscriber/call_item.py", line 172, in call
    raise e
  File "/path/to/site-packages/faststream/broker/subscriber/call_item.py", line 164, in call
    result = await call(message)
  File "/path/to/site-packages/faststream/broker/middlewares/base.py", line 73, in consume_scope
    await self.after_consume(err)
  File "/path/to/site-packages/faststream/broker/middlewares/base.py", line 54, in after_consume
    raise err
  File "/path/to/site-packages/faststream/broker/middlewares/base.py", line 64, in consume_scope
    result = await call_next(await self.on_consume(msg))
  File "/path/to/site-packages/faststream/broker/wrapper/call.py", line 201, in decode_wrapper
    return await func(msg)
  File "/path/to/site-packages/fast_depends/use.py", line 148, in injected_wrapper
    r = await real_model.asolve(
  File "/path/to/site-packages/fast_depends/core/model.py", line 533, in asolve
    response = await run_async(call, *final_args, **final_kwargs)
  File "/path/to/site-packages/fast_depends/utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
  File "/path/to/site-packages/faststream/utils/functions.py", line 53, in to_async_wrapper
    return await call_or_await(func, *args, **kwargs)
  File "/path/to/site-packages/fast_depends/utils.py", line 50, in run_async
    return await run_in_threadpool(cast(Callable[P, T], func), *args, **kwargs)
  File "/path/to/site-packages/fast_depends/utils.py", line 58, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/path/to/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/path/to/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/path/to/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "<ipython-input-1-<unique_hash>>", line 24, in my_handler
    assert msg.consumer.config['group.instance.id'] == 'instance-id-1'
AssertionError
<timestamp> INFO     - test-topic | group-id | 0-<message_id> - Processed
```

**Environment**

```
faststream -v
Running FastStream 0.5.15 with CPython 3.10.14 on Darwin
```

**Additional context**

Y'all could add first-class support for group.instance.id as a broker.suscriber() level argument.

**Comment by Lancetnik** [comment]
@andreaimprovised  thank you for the report!
But I don't think, that you suggestion is correct
In most cases the are using broker initial options as a default value, so in your case

```python
broker = KafkaBroker(config={'group.instance.id': 'instance-id-1'})
 
broker.subscriber('test-topic', group_id='group-id')   # should has `group-id` id

broker.subscriber('another-topic')   # should has `instance-id-1` id
```

Are you ok with such behavior?

**Comment by andreaimprovised** [comment]
> @andreaimprovised  thank you for the report!
> 
> But I don't think, that you suggestion is correct
> 
> In most cases the are using broker initial options as a default value, so in your case
> 
> 
> 
> ```python
> 
> broker = KafkaBroker(config={'group.instance.id': 'instance-id-1'})
> 
>  
> 
> broker.subscriber('test-topic', group_id='group-id')   # should has `group-id` id
> 
> 
> 
> broker.subscriber('another-topic')   # should has `instance-id-1` id
> 
> ```
> 
> 
> 
> Are you ok with such behavior?

It was more of a hack to get group.instance.id working. I agree that setting it on the Broker is not ideal.

I would prefer to set it on broker.subscriber() and router.subscriber() but there is not yet the capability.

**Comment by kumaranvpl** [comment]
Hello @andreaimprovised, 

Thanks for letting us know. I have somehow accidentally left out `group_instance_id` from `broker.subscriber` parameter. 
The fix is in the PR https://github.com/airtai/faststream/pull/1695. 

Once the PR is merged and new version is released, you could either use it in broker config:
```python
import asyncio
import random

from faststream import FastStream, Logger
from faststream.confluent import KafkaBroker as KafkaBroker
from faststream.confluent import KafkaMessage
from pydantic import BaseModel, Field

version = "0.1.0"
title = "My FastStream service"
description = "Description of my FastStream service"


class Name(BaseModel):
    name: str = Field(..., description="Name of the person")


class Greeting(BaseModel):
    greeting: str = Field(..., description="Greeting message")


config = {"group.instance.id": "config-instance-id-1"}
broker = KafkaBroker(config=config)
app = FastStream(broker, title=title, version=version, description=description)


topic = "names_jan_2024"

@broker.subscriber(topic, description="Consumes messages from names topic and produces messages to greetings topic", auto_offset_reset="earliest")
async def on_names(msg: Name, logger: Logger, m: KafkaMessage) -> None:
    result = f"hello {msg.name}"
    logger.info(result)
    logger.info(m.consumer.config.get("group.instance.id")) # Should print "config-instance-id-1"
    


@app.after_startup
async def publish_names() -> None:
    async def _publish_names() -> None:
        names = [
            "Ana",
            "Mario",
            "Pedro",
            "João",
            "Gustavo",
            "Joana",
            "Mariana",
            "Juliana",
        ]
        while True:
            name = random.choice(names)  # nosec
            print(f"producing {name}")
            await broker.publish(Name(name=name), topic=topic)
            
            
            
            await asyncio.sleep(2)

    asyncio.create_task(_publish_names())
```

or in subscriber parameter:
```python
import asyncio
import random

from faststream import FastStream, Logger
from faststream.confluent import KafkaBroker as KafkaBroker
from faststream.confluent import KafkaMessage
from pydantic import BaseModel, Field

version = "0.1.0"
title = "My FastStream service"
description = "Description of my FastStream service"


class Name(BaseModel):
    name: str = Field(..., description="Name of the person")


class Greeting(BaseModel):
    greeting: str = Field(..., description="Greeting message")


broker = KafkaBroker()
app = FastStream(broker, title=title, version=version, description=description)


topic = "names_jan_2024"

@broker.subscriber(topic, description="Consumes messages from names topic and produces messages to greetings topic", auto_offset_reset="earliest", group_instance_id="group-subscriber-instance-1")
async def on_names(msg: Name, logger: Logger, m: KafkaMessage) -> None:
    result = f"hello {msg.name}"
    logger.info(result)
    logger.info(m.consumer.config.get('group.instance.id')) # Should print "group-subscriber-instance-1"
    


@app.after_startup
async def publish_names() -> None:
    async def _publish_names() -> None:
        names = [
            "Ana",
            "Mario",
            "Pedro",
            "João",
            "Gustavo",
            "Joana",
            "Mariana",
            "Juliana",
        ]
        while True:
            name = random.choice(names)  # nosec
            print(f"producing {name}")
            await broker.publish(Name(name=name), topic=topic)
            
            
            
            await asyncio.sleep(2)

    asyncio.create_task(_publish_names())

```

**Comment by andreaimprovised** [comment]
@kumaranvpl looks great, thank you

Also though, fyi, the group instance ID member still participate in group rebalances. From a k8s standpoint, if a container with a spec of group instance is dies (oom, segfault) and restarts within the session timeout (so a longish session timeout), it will be able to pick back up where it left off without triggering a rebalance

And if one uses the "range" partition assignment strategy, then partition assignment is fully deterministic given a static known set of group instance IDs
