### ISSUE TITLE
Bug: FastAPI raised exception "AnyDict not defined" while adding RabbitMessage as parameter to subscriber

### ISSUE THREAD

**Issue by easyjoh** [airtai/faststream#1986]
**Describe the bug**

I am trying to amend my current FastAPI based app with subscribers for RabbitMQ.

Inside the subscriber function I need access to the full message or at least the correlation_id and the headers. However, I seem not to get acces to them from the Request parameter, thus, trying to add the `message: RabbitMessage`, but then it explodes.

On the FastApi Lifespan `yield` this following exception is raised, but *only* if the subscriber endpoint ask for RabbitMessage:

```
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 864, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, globalns=self._types_namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 279, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 303, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 332, in _eval_type
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 414, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 924, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'AnyDict' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../.venv/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/fastapi/routing.py", line 134, in merged_lifespan
    async with nested_context(app) as maybe_nested_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/fastapi/router.py", line 324, in start_broker_lifespan
    await self.broker.start()
  File "/.../.venv/lib/python3.12/site-packages/faststream/rabbit/broker/broker.py", line 508, in start
    await super().start()
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/core/usecase.py", line 219, in start
    await self.connect()
  File "/.../.venv/lib/python3.12/site-packages/faststream/rabbit/broker/broker.py", line 426, in connect
    connection = await super().connect(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/core/usecase.py", line 227, in connect
    self.setup()
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/core/usecase.py", line 238, in setup
    self.setup_subscriber(h)
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/core/usecase.py", line 251, in setup_subscriber
    subscriber.setup(**data)
  File "/.../.venv/lib/python3.12/site-packages/faststream/rabbit/subscriber/usecase.py", line 127, in setup
    super().setup(
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/subscriber/usecase.py", line 182, in setup
    call.setup(
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/subscriber/call_item.py", line 92, in setup
    dependant = self.handler.set_wrapped(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/wrapper/call.py", line 159, in set_wrapped
    call = decor(call)
           ^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/fastapi/router.py", line 231, in wrapper
    return wrap_callable_to_fastapi_compatible(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/fastapi/route.py", line 94, in wrap_callable_to_fastapi_compatible
    dependent=get_fastapi_native_dependant(user_callable, list(dependencies)),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/faststream/broker/fastapi/get_dependant.py", line 32, in get_fastapi_native_dependant
    dependent = get_dependant(
                ^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 277, in get_dependant
    param_details = analyze_param(
                    ^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 478, in analyze_param
    field = create_model_field(
            ^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/fastapi/utils.py", line 96, in create_model_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/.../.venv/lib/python3.12/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1025, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1822, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1823, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1132, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 918, in _generate_schema_inner
    return self.generate_schema(self._resolve_forward_ref(obj))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 866, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'AnyDict' is not defined

For further information visit https://errors.pydantic.dev/2.9/u/undefined-annotation

```

**How to reproduce**
Include source code:

The faststream subscriber setup:

```python
from fastapi import FastAPI, Request

from faststream.rabbit.fastapi import RabbitRouter
from faststream.rabbit import RabbitBroker, RabbitQueue, RabbitExchange
from faststream.rabbit import RabbitMessage
from faststream.types import AnyDict

@rabbit_router.subscriber(queue=action_queue, no_ack=False, retry=3, include_in_schema=False)
async def action_subscriber(request: Request, body: str, message: RabbitMessage):
    logger.info(f"Action subscriber received message: {body}")
    await publish_message(f"Action subscriber received message: {body}", exchange="logs", sub_channel='info') 

```

The App.py.

```python
from fastapi import FastAPI, status, Request

...

def create_app() -> FastAPI:
    @asynccontextmanager
    async def lifespan(app: FastAPI):
        print('lifespan start')
        yield
        print('lifespan end')

    # Pass the lifespan function to FastAPI
    app = FastAPI(
        docs_url=docs_url,
        redoc_url=redoc_url,
        openapi_url=openapi_url,
        lifespan=lifespan
    )

    # Register routes
    register_routes(app)

    return app

# Instantiate the app
app = create_app()


...
def register_routes(app: FastAPI):
    app.include_router(rabbit_router, include_in_schema=False)

```

**Comment by easyjoh** [comment]
Thank you, that fixed it.

Also:

`async def action_subscriber(request: Request, body: str, message: RabbitMessage):`

should be:

`async def action_subscriber(request: Request, body: dict, message: RabbitMessage):`
