### ISSUE TITLE
Bug:Not working without `Starelette` and/or `FastAPI`

### ISSUE THREAD

**Issue by shepilov-vladislav** [airtai/faststream#878]
**Describe the bug**
`KafkaRouter`, `NatsRouter`, `RabbitRouter` always depend on `FastAPI` and `Starelette`, even if they are not installed

**How to reproduce**
Just install to environment without `Starelette` and/or `FastAPI`

```python
faststream.kafka.router.KafkaRouter
...
```

**Expected behavior**
Should work without `Starelette` and/or `FastAPI` as dependency

**Environment**
```shell
> faststream -v
Running FastStream 0.2.7 with CPython 3.11.6 on Darwin
```

**Comment by dem214** [comment]
meet this too, have `starlette==0.22.0` so have an error on start
```sh
$ faststream
Traceback (most recent call last):
  File "project/.venv/bin/faststream", line 5, in <module>
    from faststream.__main__ import cli
  File "project/.venv/lib/python3.11/site-packages/faststream/__main__.py", line 1, in <module>
    from faststream.cli.main import cli
  File "project/.venv/lib/python3.11/site-packages/faststream/cli/main.py", line 10, in <module>
    from faststream.cli.docs.app import docs_app
  File "project/.venv/lib/python3.11/site-packages/faststream/cli/docs/app.py", line 10, in <module>
    from faststream.asyncapi.generate import get_app_schema
  File "project/.venv/lib/python3.11/site-packages/faststream/asyncapi/generate.py", line 18, in <module>
    from faststream.broker.fastapi.router import StreamRouter
  File "project/.venv/lib/python3.11/site-packages/faststream/broker/fastapi/__init__.py", line 2, in <module>
    from faststream.broker.fastapi.router import StreamRouter
  File "project/.venv/lib/python3.11/site-packages/faststream/broker/fastapi/router.py", line 30, in <module>
    from starlette.types import AppType, ASGIApp, Lifespan
ImportError: cannot import name 'AppType' from 'starlette.types' (project/.venv/lib/python3.11/site-packages/starlette/types.py)
```
